# we create a Docker image from source code
version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host(myPc):port in container)}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa@123456
      POSTGRES_DB: testdb
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

networks:
  dev-network:
